/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const Reservation = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Text,
  'name' : IDL.Text,
  'note' : IDL.Opt(IDL.Text),
  'time' : IDL.Text,
  'timestamp' : Time,
  'phoneNumber' : IDL.Text,
  'numberOfGuests' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createReservation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
  'getReservation' : IDL.Func([IDL.Nat], [Reservation], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const Reservation = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Text,
    'name' : IDL.Text,
    'note' : IDL.Opt(IDL.Text),
    'time' : IDL.Text,
    'timestamp' : Time,
    'phoneNumber' : IDL.Text,
    'numberOfGuests' : IDL.Nat,
  });
  
  return IDL.Service({
    'createReservation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'getAllReservations' : IDL.Func([], [IDL.Vec(Reservation)], ['query']),
    'getReservation' : IDL.Func([IDL.Nat], [Reservation], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };